In [141]:
options(warn = -1)
options(repr.plot.width = 15, repr.plot.height = 9)
Sys.setlocale(category = "LC_ALL", locale = "ko_KR.UTF-8")

[1] "ko_KR.UTF-8/ko_KR.UTF-8/ko_KR.UTF-8/C/ko_KR.UTF-8/C.UTF-8"

In [142]:
c(c(1, 3 ,5), 1:10, seq(1, 10, 2), rep(1:3, 2))

 [1]  1  3  5  1  2  3  4  5  6  7  8  9 10  1  3  5  7  9  1  2  3  1  2  3

In [143]:
head(iris)
irisHead <- iris[1:6,]
irisHead

  Sepal.Length Sepal.Width Petal.Length Petal.Width Species
1 5.1          3.5         1.4          0.2         setosa
2 4.9          3.0         1.4          0.2         setosa
3 4.7          3.2         1.3          0.2         setosa
4 4.6          3.1         1.5          0.2         setosa
5 5.0          3.6         1.4          0.2         setosa
6 5.4          3.9         1.7          0.4         setosa

  Sepal.Length Sepal.Width Petal.Length Petal.Width Species
1 5.1          3.5         1.4          0.2         setosa
2 4.9          3.0         1.4          0.2         setosa
3 4.7          3.2         1.3          0.2         setosa
4 4.6          3.1         1.5          0.2         setosa
5 5.0          3.6         1.4          0.2         setosa
6 5.4          3.9         1.7          0.4         setosa

In [144]:
# 행과 열을 뒤집기
t(irisHead)

             1      2      3      4      5      6
Sepal.Length 5.1    4.9    4.7    4.6    5.0    5.4
Sepal.Width  3.5    3.0    3.2    3.1    3.6    3.9
Petal.Length 1.4    1.4    1.3    1.5    1.4    1.7
Petal.Width  0.2    0.2    0.2    0.2    0.2    0.4
Species      setosa setosa setosa setosa setosa setosa

In [145]:
iris[seq(10, 150, 10), c("Sepal.Length", "Sepal.Width")]

    Sepal.Length Sepal.Width
10  4.9          3.1
20  5.1          3.8
30  4.7          3.2
40  5.1          3.4
50  5.0          3.3
60  5.2          2.7
70  5.6          2.5
80  5.7          2.6
90  5.5          2.5
100 5.7          2.8
110 7.2          3.6
120 6.0          2.2
130 7.2          3.0
140 6.9          3.1
150 5.9          3.0

In [146]:
# row 수
nrow(iris)

# column 수
ncol(iris)

length(iris)

[1] 150

[1] 5

[1] 5

In [147]:
# 기본 통계량
summary(iris)

summary(iris$Sepal.Length) # 특정 열의 기본 통계량

  Sepal.Length    Sepal.Width     Petal.Length    Petal.Width
 Min.   :4.300   Min.   :2.000   Min.   :1.000   Min.   :0.100
 1st Qu.:5.100   1st Qu.:2.800   1st Qu.:1.600   1st Qu.:0.300
 Median :5.800   Median :3.000   Median :4.350   Median :1.300
 Mean   :5.843   Mean   :3.057   Mean   :3.758   Mean   :1.199
 3rd Qu.:6.400   3rd Qu.:3.300   3rd Qu.:5.100   3rd Qu.:1.800
 Max.   :7.900   Max.   :4.400   Max.   :6.900   Max.   :2.500
       Species
 setosa    :50
 versicolor:50
 virginica :50

   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.
  4.300   5.100   5.800   5.843   6.400   7.900

In [148]:
# factor Type인 Species에서 문자와 숫자로 각각 출력하기
as.character(iris$Species)
as.numeric(iris$Species)

  [1] "setosa"     "setosa"     "setosa"     "setosa"     "setosa"
  [6] "setosa"     "setosa"     "setosa"     "setosa"     "setosa"
 [11] "setosa"     "setosa"     "setosa"     "setosa"     "setosa"
 [16] "setosa"     "setosa"     "setosa"     "setosa"     "setosa"
 [21] "setosa"     "setosa"     "setosa"     "setosa"     "setosa"
 [26] "setosa"     "setosa"     "setosa"     "setosa"     "setosa"
 [31] "setosa"     "setosa"     "setosa"     "setosa"     "setosa"
 [36] "setosa"     "setosa"     "setosa"     "setosa"     "setosa"
 [41] "setosa"     "setosa"     "setosa"     "setosa"     "setosa"
 [46] "setosa"     "setosa"     "setosa"     "setosa"     "setosa"
 [51] "versicolor" "versicolor" "versicolor" "versicolor" "versicolor"
 [56] "versicolor" "versicolor" "versicolor" "versicolor" "versicolor"
 [61] "versicolor" "versicolor" "versicolor" "versicolor" "versicolor"
 [66] "versicolor" "versicolor" "versicolor" "versicolor" "versicolor"
 [71] "versicolor" "versicolor" "versicolor" "versicolor" "versicolor"
 [76] "versicolor" "versicolor" "versicolor" "versicolor" "versicolor"
 [81] "versicolor" "versicolor" "versicolor" "versicolor" "versicolor"
 [86] "versicolor" "versicolor" "versicolor" "versicolor" "versicolor"
 [91] "versicolor" "versicolor" "versicolor" "versicolor" "versicolor"
 [96] "versicolor" "versicolor" "versicolor" "versicolor" "versicolor"
[101] "virginica"  "virginica"  "virginica"  "virginica"  "virginica"
[106] "virginica"  "virginica"  "virginica"  "virginica"  "virginica"
[111] "virginica"  "virginica"  "virginica"  "virginica"  "virginica"
[116] "virginica"  "virginica"  "virginica"  "virginica"  "virginica"
[121] "virginica"  "virginica"  "virginica"  "virginica"  "virginica"
[126] "virginica"  "virginica"  "virginica"  "virginica"  "virginica"
[131] "virginica"  "virginica"  "virginica"  "virginica"  "virginica"
[136] "virginica"  "virginica"  "virginica"  "virginica"  "virginica"
[141] "virginica"  "virginica"  "virginica"  "virginica"  "virginica"
[146] "virginica"  "virginica"  "virginica"  "virginica"  "virginica"

  [1] 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 [38] 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 [75] 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 3
[112] 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
[149] 3 3

In [149]:
# 벡터 계산
x <- c(3, 6, 9, 12, 15)
x + 1

# 벡터 계산에서는 길이를 맞춰야 한다.
y <- c(1, 2, 3, 4, 5)

if (length(x) == length(y)) {
    print(x + y)
} else {
    print("done")
}

[1]  4  7 10 13 16

[1]  4  8 12 16 20

In [150]:
# 벡터 합치기
x <- c(10, 20, 30, 40, 50)
y <- c(1, 2, 3)
sort(append(x, y)) # 위치 지정 가능

sort(c(x, y)) # 일반적으로 사용됨

[1]  1  2  3 10 20 30 40 50

[1]  1  2  3 10 20 30 40 50

In [151]:
# Ex. iris의 Sepal.Length의 중복되지 않은 개수의 percent를 구하기
(length(unique(iris$Sepal.Length)) / length(iris$Sepal.Length)) * 100

[1] 23.33333

In [152]:
# Ex. iris의 Sepal.Length의 중복된 개수의 percent를 구하기
(1- (length(unique(iris$Sepal.Length)) / length(iris$Sepal.Length))) * 100

[1] 76.66667

#### 문자열 관련 함수

In [153]:
paste("Hello", "World!")

[1] "Hello World!"

In [154]:
paste(iris$Species[1], ":", iris$Species[51], ":", iris$Species[101])

[1] "setosa : versicolor : virginica"

In [155]:
paste("010", "1111", "2222", sep = "-")

[1] "010-1111-2222"

In [156]:
# 문자열 꾸미기
cat("Hello", "\n", "World!\n")
cat("aaa\tbbb\tccc")

Hello
 World!
aaa	bbb	ccc

In [157]:
# 문자열 추출하기
str01 <- "Hello World!"
substring(str01, 1, 5) # Hello

str02 <- "가나다라마바사"
substring(str02, 2, 5) # 나다라마

[1] "Hello"

[1] "나다라마"

In [158]:
x <- runif(5, 1, 20) # runif(개수, 최소값, 최대값) : 1부터 20 사이의 난수 5개를 생성해서 x에 저장
x

[1] 16.363699  4.056859  6.291235  5.796797  8.538580

In [159]:
# x와 값들이 4와 7 사이에 있는지 확인
(x >= 4) & (x <= 7)

[1] FALSE  TRUE  TRUE  TRUE FALSE

In [160]:
# 데이터 개수
sum((x >= 4) & (x <= 7))

[1] 3

In [161]:
# any, all
any(x >= 10) # 1개라도 10보다 크면 TRUE
all(x >= 10) # 모든 값을 확인

[1] TRUE

[1] FALSE

#### 행렬(Matrix)
: 데이터의 모든 Type이 일치되어야 구성됨

In [162]:
vec1 <- c(1, 2, 3)
vec2 <- c(4, 5, 6)
vec3 <- c(7, 8, 9)

In [163]:
# rbind: row bind
mat1 <- rbind(vec1, vec2, vec3)
mat1

     [,1] [,2] [,3]
vec1 1    2    3
vec2 4    5    6
vec3 7    8    9

In [164]:
# cbind: column bind
mat2 <- cbind(vec1, vec2, vec3)
mat2

     vec1 vec2 vec3
[1,] 1    4    7
[2,] 2    5    8
[3,] 3    6    9

In [165]:
irisHead <- head(iris, 5)

irisHead <- rbind(irisHead, c(1, 1, 1, 1, 'setosa'))

irisHead <- cbind(irisHead, abc = rep(2, 6))

irisHead

  Sepal.Length Sepal.Width Petal.Length Petal.Width Species abc
1 5.1          3.5         1.4          0.2         setosa  2
2 4.9          3           1.4          0.2         setosa  2
3 4.7          3.2         1.3          0.2         setosa  2
4 4.6          3.1         1.5          0.2         setosa  2
5 5            3.6         1.4          0.2         setosa  2
6 1            1           1            1           setosa  2

In [166]:
irisHead <- iris[1:5,]

# 열 추가하기
# Length = Sepal.Length + Petal.Length
irisHead <- cbind(irisHead, Length = irisHead$Sepal.Length + irisHead$Petal.Length)
irisHead$Length2 <- irisHead$Sepal.Length + irisHead$Petal.Length

irisHead

  Sepal.Length Sepal.Width Petal.Length Petal.Width Species Length Length2
1 5.1          3.5         1.4          0.2         setosa  6.5    6.5
2 4.9          3.0         1.4          0.2         setosa  6.3    6.3
3 4.7          3.2         1.3          0.2         setosa  6.0    6.0
4 4.6          3.1         1.5          0.2         setosa  6.1    6.1
5 5.0          3.6         1.4          0.2         setosa  6.4    6.4

In [167]:
mat1
colnames(mat1) <- c("A", "B", "C")
mat1
class(mat1)

mat1D <- as.data.frame(mat1)
mat1D

     [,1] [,2] [,3]
vec1 1    2    3
vec2 4    5    6
vec3 7    8    9

     A B C
vec1 1 2 3
vec2 4 5 6
vec3 7 8 9

[1] "matrix" "array"

     A B C
vec1 1 2 3
vec2 4 5 6
vec3 7 8 9

In [168]:
mat2
rownames(mat2) <- 1:3
mat2

mat2D <- as.data.frame(mat2)
mat2D

     vec1 vec2 vec3
[1,] 1    4    7
[2,] 2    5    8
[3,] 3    6    9

  vec1 vec2 vec3
1 1    4    7
2 2    5    8
3 3    6    9

  vec1 vec2 vec3
1 1    4    7
2 2    5    8
3 3    6    9

In [169]:
mat1D
mat2D

     A B C
vec1 1 2 3
vec2 4 5 6
vec3 7 8 9

  vec1 vec2 vec3
1 1    4    7
2 2    5    8
3 3    6    9

In [170]:
colnames(mat2D) <- colnames(mat1D) # col 이름 통일
rbind(mat1D, mat2D) # col 이름이 다르면 bind 오류

     A B C
vec1 1 2 3
vec2 4 5 6
vec3 7 8 9
1    1 4 7
2    2 5 8
3    3 6 9

In [171]:
colnames(mat2D)

[1] "A" "B" "C"

#### 데이터프레임
: 다양한 자료형으로 구성된 2차원 형태의 데이터 구조

In [172]:
# 벡터로 데이터프레임 만들기
no <- 1:4
name <- c("Apple", "Banana", "Peach", "Berry")
price <- c(500, 400, 300, 200)
qty <- c(5, 2, 7, 9)

In [173]:
fruit <- data.frame(번호=no, 상품명=name, 금액=price, 재고량=qty)
fruit

  번호 상품명 금액 재고량
1 1    Apple  500  5
2 2    Banana 400  2
3 3    Peach  300  7
4 4    Berry  200  9

In [174]:
str(fruit)

'data.frame':	4 obs. of  4 variables:
 $ 번호  : int  1 2 3 4
 $ 상품명: chr  "Apple" "Banana" "Peach" "Berry"
 $ 금액  : num  500 400 300 200
 $ 재고량: num  5 2 7 9

In [175]:
# fruit에서 상품명과 재고량만 보기
fruit[,c(2, 4)]

  상품명 재고량
1 Apple  5
2 Banana 2
3 Peach  7
4 Berry  9

In [176]:
#fruit에서 번호를 제외한 모든 내용 보기
fruit[,-1]#-1 삭제 행과열 구분 2차원 데이터

  상품명 금액 재고량
1 Apple  500  5
2 Banana 400  2
3 Peach  300  7
4 Berry  200  9

In [177]:
#fruit에서 2,4 번 행을 제외한 상품명, 금액, 재고량만 최소한의 코딩으로
fruit[-c(2,4),-1]

  상품명 금액 재고량
1 Apple  500  5
3 Peach  300  7

In [178]:
#fruit에 재고금액(금액*재고량) 추가하기
fruit$'재고금액'=fruit$'금액'*fruit$'재고량'#타입 데이터 프레임
fruit

  번호 상품명 금액 재고량 재고금액
1 1    Apple  500  5      2500
2 2    Banana 400  2       800
3 3    Peach  300  7      2100
4 4    Berry  200  9      1800

In [179]:
fruit$'원산지'<- c('한국','태국','한국','중국')
fruit

  번호 상품명 금액 재고량 재고금액 원산지
1 1    Apple  500  5      2500     한국
2 2    Banana 400  2       800     태국
3 3    Peach  300  7      2100     한국
4 4    Berry  200  9      1800     중국

In [180]:
# irisHead <- cbind(irisHead, Length = irisHead$Sepal.Length + irisHead$Petal.Length)
# irisHead$Length2 <- irisHead$Sepal.Length + irisHead$Petal.Length

#외부 File 불러오기

In [181]:
# txt file 불러오기
read.table("../Data/emp.txt",header =  T)
# read.csv("../Data/")
read.table("../Data/emp.txt",header =  T, sep = ",")#컬럼이름 없을시 V1..., 헤더 있음

  사번.이름.급여
1 101,hong,150
2 201,lee,250
3 301,kim,300

  사번 이름 급여
1 101  hong 150
2 201  lee  250
3 301  kim  300

In [182]:
txtEmp <- read.table("../Data/emp.txt",header =  T, sep = ",")
str(txtEmp)

'data.frame':	3 obs. of  3 variables:
 $ 사번: int  101 201 301
 $ 이름: chr  "hong" "lee" "kim"
 $ 급여: int  150 250 300

In [183]:
#comma seperated value
csvEmp<-read.csv("../Data/emp2.csv", header=F)
colnames(csvEmp) <- c("사번","이름","급여")
csvEmp#파이썬 컬럼이름 변경 rename?#벡터이름:names

  사번 이름   급여
1 101  홍길동 150
2 102  이순신 450
3 103  강감찬 500
4 104  유관순 350
5 105  김유신 400

In [184]:
#컬럼 몇개?
ncol(csvEmp)

[1] 3

In [185]:
#로우 몇개?
nrow(csvEmp)

[1] 5

In [186]:
#dataFrame 생성
df <- data.frame(
    x = 1:5,
    y = seq(2,10,2),
    z=c("a","b","c","d","e")
)
df

  x y  z
1 1  2 a
2 2  4 b
3 3  6 c
4 4  8 d
5 5 10 e

In [187]:
# x와 y의 합계#데이터 프레임은 벡터들의 집합
sum=df$x+df$y
sum

[1]  3  6  9 12 15

In [188]:
sum(df$x)
sum(df$y)

[1] 15

[1] 30

#함수를 부르는 함수 .apply

In [189]:
apply(df[,1:2], 2, sum)#x와 y#행=1,열=2
apply(df[,1:2], 2, mean)
apply(df[,1:2], 2, sd)

 x  y
15 30

x y
3 6

       x        y
1.581139 3.162278

In [190]:
apply(df[,1:2],1,sum)#행방향 오른쪽
apply(df[,1:2],1,mean)

[1]  3  6  9 12 15

[1] 1.5 3.0 4.5 6.0 7.5

In [191]:
df#컬럼 만들어서 쓰기
df$Hap <- apply(df[,1:2],1,sum)
df

  x y  z
1 1  2 a
2 2  4 b
3 3  6 c
4 4  8 d
5 5 10 e

  x y  z Hap
1 1  2 a  3
2 2  4 b  6
3 3  6 c  9
4 4  8 d 12
5 5 10 e 15

In [192]:
#java compile언어 #데이터 2개
#부분집합(데이터 조건으로 찾기)
subset(df, x>=3 & y>=8)#불리언 인덱싱

  x y  z Hap
4 4  8 d 12
5 5 10 e 15

In [193]:
nrow(subset(df, x>=3 & y>=8))#로우=레코드

[1] 2

In [194]:
#두개 이상의 데이터프레임 병합
#merge/concat
height = data.frame(id=1:3, height=c(160, 170, 180))
weight = data.frame(id=c(2,1,3), weight=c(70,60,80))
height
weight
#cbine로 컬럼을 합치면 아이디가 맞지 않음

  id height
1 1  160
2 2  170
3 3  180

  id weight
1 2  70
2 1  60
3 3  80

In [195]:
merge(height, weight)#키 순서를 매치함

  id height weight
1 1  160    60
2 2  170    70
3 3  180    80

In [196]:
height = data.frame(id=1:3, height=c(160, 170, 180))
weight = data.frame(ad=c(2,1), weight=c(70,60))
height
weight

  id height
1 1  160
2 2  170
3 3  180

  ad weight
1 2  70
2 1  60

In [197]:
merge(height, weight)#outerjoin:하나씩 대칭

  id height ad weight
1 1  160    2  70
2 2  170    2  70
3 3  180    2  70
4 1  160    1  60
5 2  170    1  60
6 3  180    1  60

In [198]:
merge(x=height, y=weight, by.x = "id", by.y = "ad")#innerjoin

  id height weight
1 1  160    60
2 2  170    70

In [199]:
merge(x=height, y=weight, by.x = "id", by.y = "ad", all.x = T)#leftjoin(join=merge)

  id height weight
1 1  160    60
2 2  170    70
3 3  180    NA

In [200]:
matrix(1:10)
matrix(1:10, nrow = 2)
matrix(1:9,nrow = 3,ncol = 3)#차원 바꿈 reshape

      [,1]
 [1,]  1
 [2,]  2
 [3,]  3
 [4,]  4
 [5,]  5
 [6,]  6
 [7,]  7
 [8,]  8
 [9,]  9
[10,] 10

     [,1] [,2] [,3] [,4] [,5]
[1,] 1    3    5    7     9
[2,] 2    4    6    8    10

     [,1] [,2] [,3]
[1,] 1    4    7
[2,] 2    5    8
[3,] 3    6    9

List
- 성격이 다른 자료구조로 생성이 가능
- key와 value로 구성

In [201]:
member <- list(name="홍길동", address="서울", tel="010-1111-2222")

In [202]:
member$address

[1] "서울"

#문자열 처리
수집한 데이터의 필요한 문자열을 자르고, 교체하고 추출하는 작업
#string package 사용 : 강력
-str_length() : 문자열 길이
-str_c() : 문자열 연결
-str_sub() : 범위에 해당하는 문자열 생성
-str_split() : 구분자를 기준으로 문자열을 분리하여 부분 생성
-str_replace() : 기존 문자열을 특정 문자열로 변환
-str_extract() : 문자열에서 특정 문자열 패턴의 첫번째 문자열 추출
-str_extract_all() : 모든 문자열 추출
-str_locate():문자열에서 특정 문자열 패턴의 첫번째 위치 추출
-str_locate_all():->모든 문자열 추출

In [203]:
install.packages("stringr")

The downloaded binary packages are in
	/var/folders/bn/b43j8ymd33x1z80xxsm606h40000gn/T//RtmpzfAvXN/downloaded_packages

In [204]:
library(stringr)

In [205]:
string <- "hongkildong105yoube1002kwanwoo25장비2005"

In [206]:
#r 벡터
#a~z까지의 영문자가 연속으로 3개 발견된 문자열 추출
str_extract_all(string, "[a-z]{3}")

[[1]]
[1] "hon" "gki" "ldo" "you" "kwa" "nwo"

In [207]:
#a~z까지의 영문자가 연속으로 3~5개 발견된 문자열 추출
str_extract_all(string, "[a-z]{3,5}")

[[1]]
[1] "hongk" "ildon" "yoube" "kwanw"

In [208]:
#a~z까지의 영문자가 연속으로 1개이상 발견된 문자열 추출
aaa <- str_extract_all(string, "[a-z]{1,}")
aaa
class(aaa)
bbb <- unlist(aaa)
bbb #벡터
#substring안된다..?

[[1]]
[1] "hongkildong" "yoube"       "kwanwoo"

[1] "list"

[1] "hongkildong" "yoube"       "kwanwoo"

In [209]:
#숫자만 추출하기
str_extract_all(string, "[0-9]{1,}")#<<<<<

[[1]]
[1] "105"  "1002" "25"   "2005"

In [210]:
aaa <- str_extract_all(string, "[0-9]{1,}")
aaa <- unlist(aaa)

In [211]:
aaa<- as.numeric(unlist(aaa))
aaa

[1]  105 1002   25 2005

In [212]:
#한글만 추출하기#ascii코드 table기준? 완성형
aaa <- str_extract_all(string, "[가-힣]{1,}")
aaa <- unlist(aaa)
aaa

[1] "장비"

In [213]:
# 영문자를 제외한 문자 출력하기
str_extract_all(string, "[a-z]{1,}")
str_extract_all(string, "[^a-z]{1,}")

[[1]]
[1] "hongkildong" "yoube"       "kwanwoo"

[[1]]
[1] "105"        "1002"       "25장비2005"

In [214]:
#문자열 길이 구하기
str_length(string)

[1] 38

In [215]:
#문자열 위치 구하기 #정제 할때 사용? substring못씀
str_locate(string, "장비")

     start end
[1,] 33    34

In [216]:
string

[1] "hongkildong105yoube1002kwanwoo25장비2005"

In [217]:
###########################
str_sub(string, 1, 32)#장비 앞
str_sub(string, 1, str_locate(string, "장비")[1])
str_sub(string, 1, str_locate(string, "장비")[1]-1)
###############################

[1] "hongkildong105yoube1002kwanwoo25"

[1] "hongkildong105yoube1002kwanwoo25장"

[1] "hongkildong105yoube1002kwanwoo25"

In [218]:
#대문자 소문자 변경하기
str_to_upper(string)
str_to_lower(string)

[1] "HONGKILDONG105YOUBE1002KWANWOO25장비2005"

[1] "hongkildong105yoube1002kwanwoo25장비2005"

In [219]:
#문자열 교체하기 replace
string <- str_replace(string, "hongkildong105", "홍길동35,")
string <- str_replace(string, "yoube1002", "유비45,")
string <- str_replace(string, "kwanwoo25", "관우25,")
string <- str_replace(string, "2005", "20,")

In [220]:
#문자열 분리하기 split
str_split(string,",")
unlist(str_split(string,","))

[[1]]
[1] "홍길동35" "유비45"   "관우25"   "장비20"   ""

[1] "홍길동35" "유비45"   "관우25"   "장비20"   ""

In [221]:
#천단위 숫자가 들어간 문자열을 숫자로 변경하기
price <- "123,456,789"
str_replace_all(price,",","")

[1] "123456789"

In [222]:
as.numeric(str_replace_all(price,",",""))

[1] 123456789

In [223]:
as.numeric(str_remove_all(price,","))

[1] 123456789

In [224]:
#NA를 변경하기
temp <- c(1,2,NA,4)
temp
str_replace_na(temp)

[1]  1  2 NA  4

[1] "1"  "2"  "NA" "4"

In [225]:
str_replace_all(str_replace_na(temp),'NA',"3")

[1] "1" "2" "3" "4"

In [226]:
as.numeric(str_replace_all(str_replace_na(temp),'NA',"3"))

[1] 1 2 3 4

In [227]:
#NA 제거하기
temp <- c(1,2,NA,4)
temp
na.omit(temp)#<<<<<<<<<<<<<<

[1]  1  2 NA  4

[1] 1 2 4
attr(,"na.action")
[1] 3
attr(,"class")
[1] "omit"